package com.ieltsjuice.util

const val imageURL = "https://ieltsjuice.com/wp-content/uploads/app/opt/img_test_"
const val youtubeBaseURL = "https://www.googleapis.com/youtube/v3/"
const val youtubeVideoBaseURL = "https://www.youtube.com/watch?v="
const val youTubeApiKey = "AIzaSyAk79gPVoTkRkf6v0Ex2dZfofP-FfyqDso"
const val channelId = "UCEQsKthXP6uB6_iHe0wCyXQ"
const val listeningPlayList = "PLzv4_7S0bZm86T7-mXOboGQW4mG0eEZ2k"
const val speakingPlayList = "PLzv4_7S0bZm8fElqL8Z0yIITCr6EL8xsR"
const val writingPlayList = "PLzv4_7S0bZm9P-QzJuElntXRoWp-ehm6i"
const val readingPlayList = "PLzv4_7S0bZm_OJuhBdOW-taU4poqz4xxr"
const val overViewPlayList = "PLzv4_7S0bZm8Uas-cOG38oCPXBMUzmX5A"

const val dictionaryBaseURL = "https://api.dictionaryapi.dev/api/v2/entries/en/"

const val KEY_teacherName = "KEY_teacherName"
const val KEY_teacherFamily = "KEY_teacherFamily"
const val KEY_teacherTitle = "KEY_teacherTitle"
const val KEY_teacherDesc = "KEY_teacherDesc"
const val KEY_teacherInstagram = "KEY_teacherInstagram"
const val KEY_teacherLinkedin = "KEY_teacherLinkedin"
const val KEY_teacherFacebook = "KEY_teacherFacebook"
const val KEY_teacherSkype = "KEY_teacherSkype"
const val KEY_teacherWebpage = "KEY_teacherWebpage"
const val KEY_teacherImage = "KEY_teacherImage"
const val PAGE_NAME_KEY = "PAGE_NAME_KEY"
